FROM apache:2.4.33

MAINTAINER nazwisko + emial

USER root

ENV WWW_DIR /usr/local/apache2/htdocs/

COPY ./html/ $WWW_DIR



#budowanie dockera - docker build -t katalog_projektu

CMD vs ENTRYPOINT
https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact
https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
